import os
from dotenv import load_dotenv

load_dotenv()


class Settings:
    # Your Telegram account credentials
    API_ID: int = int(os.getenv("API_ID", "0"))
    API_HASH: str = os.getenv("API_HASH", "")

    # String session for YOUR account (generated by generate_session.py)
    STRING_SESSION: str = os.getenv("STRING_SESSION", "")

    # Spotify credentials
    SPOTIFY_CLIENT_ID: str = os.getenv("SPOTIFY_CLIENT_ID", "")
    SPOTIFY_CLIENT_SECRET: str = os.getenv("SPOTIFY_CLIENT_SECRET", "")

    # MongoDB
    MONGO_URI: str = os.getenv("MONGO_URI", "mongodb://localhost:27017")
    DB_NAME: str = os.getenv("DB_NAME", "music_bot")

    # Bot settings
    DEFAULT_VOLUME: int = int(os.getenv("DEFAULT_VOLUME", "100"))
    AUDIO_QUALITY: str = os.getenv("AUDIO_QUALITY", "192")  # kbps
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")

    # Command prefix — what your userbot responds to (default: /)
    CMD_PREFIX: str = os.getenv("CMD_PREFIX", "/")

    # Comma-separated Telegram user IDs who can use admin commands
    # Add your own user ID here so YOU always have full control
    ADMIN_IDS: list[int] = [
        int(uid.strip())
        for uid in os.getenv("ADMIN_IDS", "").split(",")
        if uid.strip().isdigit()
    ]

    def validate(self) -> None:
        """Raise an error if required settings are missing."""
        missing = []
        required = {
            "API_ID": self.API_ID,
            "API_HASH": self.API_HASH,
            "STRING_SESSION": self.STRING_SESSION,
            "SPOTIFY_CLIENT_ID": self.SPOTIFY_CLIENT_ID,
            "SPOTIFY_CLIENT_SECRET": self.SPOTIFY_CLIENT_SECRET,
            "MONGO_URI": self.MONGO_URI,
        }
        for key, value in required.items():
            if not value or value == 0:
                missing.append(key)
        if missing:
            raise EnvironmentError(
                f"Missing required environment variables: {', '.join(missing)}"
            )
